//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DEFAULT.RC
//
#define IDS_APPNAME                     1
#define IDS_WINDOWNAME                  2
#define ID_HELP_ABOUT                   40001
#define IDM_ONLINE                      40002
#define IDM_OFFLINE                     40003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
