//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by default.rc
//
#define IDS_E001                        1
#define IDS_E002                        2
#define IDS_E003                        3
#define IDS_E004                        4
#define IDS_E005                        5
#define IDS_E006                        6
#define IDS_E007                        7
#define IDS_E008                        8
#define IDS_E020                        9
#define IDS_E021                        10
#define IDS_E022                        11
#define IDS_E023                        12
#define IDS_E024                        13
#define IDS_E040                        14
#define IDS_E041                        15
#define IDS_E042                        16
#define IDS_E043                        17
#define IDS_E044                        18
#define IDS_E060                        19
#define IDS_E061                        20
#define IDS_E080                        21
#define IDS_E081                        22
#define IDS_E082                        23
#define IDS_E083                        24
#define IDS_E084                        25
#define IDS_E100                        26
#define IDS_E101                        27
#define IDS_E102                        28
#define IDS_E120                        29
#define IDS_E130                        30
#define IDS_E131                        31
#define IDD_MAIN                        101
#define IDI_APPL                        102
#define IDC_CREATE                      1000
#define IDC_EDIT2                       1002
#define IDC_START                       1002
#define IDC_EDIT3                       1003
#define IDC_END                         1003
#define IDC_OUTPUT                      1004
#define IDC_OPTION                      1005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
