//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DEFAULT.RC
//
#define IDS_APPNAME                     1
#define IDS_WINDOWNAME                  2
#define IDS_BAUDRATE                    3
#define IDS_DATABIT                     4
#define IDS_PARITYBIT                   5
#define IDS_STOPBIT                     6
#define IDS_COMPORT                     7
#define IDI_ICON1                       104
#define PRESTER                         104
#define PRESTAR                         104
#define IDB_PARENT                      107
#define IDB_CHILD                       108
#define IDB_TRANCE1                     109
#define IDB_TRANCE2                     110
#define IDB_TRANCE3                     111
#define IDB_TRANCE4                     112
#define IDB_TRANCE5                     113
#define IDC_EDIT_MODE                   1002
#define IDC_EDIT_STAT                   1003
#define IDC_EDIT_TIMEOUT                1004
#define IDC_EDIT_RETRY                  1005
#define IDC_2400                        1008
#define IDC_4800                        1009
#define IDC_9600                        1010
#define IDC_19200                       1011
#define IDC_DATA                        1012
#define IDC_DAT5                        1013
#define IDC_DAT6                        1014
#define IDC_DAT7                        1015
#define IDC_DAT8                        1016
#define IDC_PARITY                      1017
#define IDC_NONE                        1018
#define IDC_ODD                         1019
#define IDC_EVEN                        1020
#define IDC_38400                       1021
#define IDC_STOP                        1022
#define IDC_STOP1                       1023
#define IDC_STOP15                      1024
#define IDC_STOP2                       1025
#define IDC_COM                         1027
#define IDC_COM1                        1028
#define IDC_COM2                        1029
#define IDC_COM3                        1030
#define IDC_COM4                        1031
#define ID_HELP_ABOUT                   40001
#define IDM_ONLINE                      40002
#define IDM_OFFLINE                     40003
#define IDM_GRP00                       40004
#define IDM_VIEW_STATUS                 40005
#define IDM_FILE_EXIT                   40006
#define IDM_GRP01                       40007
#define IDM_GRP02                       40008
#define IDM_LOG                         40010
#define IDM_COMSET                      40011
#define IDM_PLOG                        40012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40013
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
