'###########################################################
'# StrConv ÇÃÉNÉçÅ[ÉìÇ∑ÇÈä÷êî
'#                                        çÏê¨ Ç‹Ç¡Ç¬ÇÒ
'#              http://hp.vector.co.jp/authors/VA020411
'#              mattn@mail.goo.ne.jp
'###########################################################

'***************************************************
' StrConvUpperCase
'---------------------------------------------------
' ópìr : StrConv(sInp,vbUpperCase) ÇÃÉNÉçÅ[Éì
' à¯êî : ïœä∑Ç∑ÇÈï∂éöóÒ
' ñﬂíl : ïœä∑Ç≥ÇÍÇΩï∂éöóÒ
'***************************************************
Function StrConvUpperCase(sInp)
	StrConvUpperCase = UCase(sInp)
End Function

'***************************************************
' StrConvLowerCase
'---------------------------------------------------
' ópìr : StrConv(sInp,vbLowerCase) ÇÃÉNÉçÅ[Éì
' à¯êî : ïœä∑Ç∑ÇÈï∂éöóÒ
' ñﬂíl : ïœä∑Ç≥ÇÍÇΩï∂éöóÒ
'***************************************************
Function StrConvLowerCase(sInp)
	StrConvLowerCase = LCase(sInp)
End Function

'***************************************************
' StrConvProperCase
'---------------------------------------------------
' ópìr : StrConv(sInp,vbProperCase) ÇÃÉNÉçÅ[Éì
' à¯êî : ïœä∑Ç∑ÇÈï∂éöóÒ
' ñﬂíl : ïœä∑Ç≥ÇÍÇΩï∂éöóÒ
'***************************************************
Function StrConvProperCase(sInp)
	Dim nPos
	Dim nSpc

	nPos = 1
	Do While InStr(nPos, sInp, " ", 1) <> 0
		nSpc = InStr(nPos, sInp, " ", 1)
		StrConvProperCase = StrConvProperCase & UCase(Mid(sInp, nPos, 1))
		StrConvProperCase = StrConvProperCase & LCase(Mid(sInp, nPos + 1, nSpc - nPos))
		nPos = nSpc + 1
	Loop

	StrConvProperCase = StrConvProperCase & UCase(Mid(sInp, nPos, 1))
	StrConvProperCase = StrConvProperCase & LCase(Mid(sInp, nPos + 1))
	StrConvProperCase = StrConvProperCase
End Function

'***************************************************
' StrConvWide
'---------------------------------------------------
' ópìr : StrConv(s,vbWide) ÇÃÉNÉçÅ[Éì
' à¯êî : ïœä∑Ç∑ÇÈï∂éöóÒ
' ñﬂíl : ïœä∑Ç≥ÇÍÇΩï∂éöóÒ
'***************************************************
Function StrConvWide(s)
	Dim nCnt
	Dim nLen
	Dim sChr
	Dim sMud

	nLen = Len(s)
	For nCnt = 1 To nLen
		sChr = Mid(s,nCnt,1)
		sMud = Mid(s,nCnt+1,1) 
		If InStr("ﬁﬂ", sMud) Then
			sChr = sChr & sMud
			nCnt = nCnt + 1
		End If
		Select Case sChr
		Case " "
			StrConvWide = StrConvWide & "Å@"
		Case "!"
			StrConvWide = StrConvWide & "ÅI"
		Case """"
			StrConvWide = StrConvWide & "˙W"
		Case "#"
			StrConvWide = StrConvWide & "Åî"
		Case "$"
			StrConvWide = StrConvWide & "Åê"
		Case "%"
			StrConvWide = StrConvWide & "Åì"
		Case "&"
			StrConvWide = StrConvWide & "Åï"
		Case "'"
			StrConvWide = StrConvWide & "˙V"
		Case "("
			StrConvWide = StrConvWide & "Åi"
		Case ")"
			StrConvWide = StrConvWide & "Åj"
		Case "*"
			StrConvWide = StrConvWide & "Åñ"
		Case "+"
			StrConvWide = StrConvWide & "Å{"
		Case ","
			StrConvWide = StrConvWide & "ÅC"
		Case "-"
			StrConvWide = StrConvWide & "Å|"
		Case "."
			StrConvWide = StrConvWide & "ÅD"
		Case "/"
			StrConvWide = StrConvWide & "Å^"
		Case "0"
			StrConvWide = StrConvWide & "ÇO"
		Case "1"
			StrConvWide = StrConvWide & "ÇP"
		Case "2"
			StrConvWide = StrConvWide & "ÇQ"
		Case "3"
			StrConvWide = StrConvWide & "ÇR"
		Case "4"
			StrConvWide = StrConvWide & "ÇS"
		Case "5"
			StrConvWide = StrConvWide & "ÇT"
		Case "6"
			StrConvWide = StrConvWide & "ÇU"
		Case "7"
			StrConvWide = StrConvWide & "ÇV"
		Case "8"
			StrConvWide = StrConvWide & "ÇW"
		Case "9"
			StrConvWide = StrConvWide & "ÇX"
		Case ":"
			StrConvWide = StrConvWide & "ÅF"
		Case ";"
			StrConvWide = StrConvWide & "ÅG"
		Case "<"
			StrConvWide = StrConvWide & "ÅÉ"
		Case "="
			StrConvWide = StrConvWide & "ÅÅ"
		Case ">"
			StrConvWide = StrConvWide & "ÅÑ"
		Case "?"
			StrConvWide = StrConvWide & "ÅH"
		Case "@"
			StrConvWide = StrConvWide & "Åó"
		Case "A"
			StrConvWide = StrConvWide & "Ç`"
		Case "B"
			StrConvWide = StrConvWide & "Ça"
		Case "C"
			StrConvWide = StrConvWide & "Çb"
		Case "D"
			StrConvWide = StrConvWide & "Çc"
		Case "E"
			StrConvWide = StrConvWide & "Çd"
		Case "F"
			StrConvWide = StrConvWide & "Çe"
		Case "G"
			StrConvWide = StrConvWide & "Çf"
		Case "H"
			StrConvWide = StrConvWide & "Çg"
		Case "I"
			StrConvWide = StrConvWide & "Çh"
		Case "J"
			StrConvWide = StrConvWide & "Çi"
		Case "K"
			StrConvWide = StrConvWide & "Çj"
		Case "L"
			StrConvWide = StrConvWide & "Çk"
		Case "M"
			StrConvWide = StrConvWide & "Çl"
		Case "N"
			StrConvWide = StrConvWide & "Çm"
		Case "O"
			StrConvWide = StrConvWide & "Çn"
		Case "P"
			StrConvWide = StrConvWide & "Ço"
		Case "Q"
			StrConvWide = StrConvWide & "Çp"
		Case "R"
			StrConvWide = StrConvWide & "Çq"
		Case "S"
			StrConvWide = StrConvWide & "Çr"
		Case "T"
			StrConvWide = StrConvWide & "Çs"
		Case "U"
			StrConvWide = StrConvWide & "Çt"
		Case "V"
			StrConvWide = StrConvWide & "Çu"
		Case "W"
			StrConvWide = StrConvWide & "Çv"
		Case "X"
			StrConvWide = StrConvWide & "Çw"
		Case "Y"
			StrConvWide = StrConvWide & "Çx"
		Case "Z"
			StrConvWide = StrConvWide & "Çy"
		Case "["
			StrConvWide = StrConvWide & "Åm"
		Case "]"
			StrConvWide = StrConvWide & "Ån"
		Case "^"
			StrConvWide = StrConvWide & "ÅO"
		Case "_"
			StrConvWide = StrConvWide & "ÅQ"
		Case "`"
			StrConvWide = StrConvWide & "ÅM"
		Case "a"
			StrConvWide = StrConvWide & "ÇÅ"
		Case "b"
			StrConvWide = StrConvWide & "ÇÇ"
		Case "c"
			StrConvWide = StrConvWide & "ÇÉ"
		Case "d"
			StrConvWide = StrConvWide & "ÇÑ"
		Case "e"
			StrConvWide = StrConvWide & "ÇÖ"
		Case "f"
			StrConvWide = StrConvWide & "ÇÜ"
		Case "g"
			StrConvWide = StrConvWide & "Çá"
		Case "h"
			StrConvWide = StrConvWide & "Çà"
		Case "i"
			StrConvWide = StrConvWide & "Çâ"
		Case "j"
			StrConvWide = StrConvWide & "Çä"
		Case "k"
			StrConvWide = StrConvWide & "Çã"
		Case "l"
			StrConvWide = StrConvWide & "Çå"
		Case "m"
			StrConvWide = StrConvWide & "Çç"
		Case "n"
			StrConvWide = StrConvWide & "Çé"
		Case "o"
			StrConvWide = StrConvWide & "Çè"
		Case "p"
			StrConvWide = StrConvWide & "Çê"
		Case "q"
			StrConvWide = StrConvWide & "Çë"
		Case "r"
			StrConvWide = StrConvWide & "Çí"
		Case "s"
			StrConvWide = StrConvWide & "Çì"
		Case "t"
			StrConvWide = StrConvWide & "Çî"
		Case "u"
			StrConvWide = StrConvWide & "Çï"
		Case "v"
			StrConvWide = StrConvWide & "Çñ"
		Case "w"
			StrConvWide = StrConvWide & "Çó"
		Case "x"
			StrConvWide = StrConvWide & "Çò"
		Case "y"
			StrConvWide = StrConvWide & "Çô"
		Case "z"
			StrConvWide = StrConvWide & "Çö"
		Case "{"
			StrConvWide = StrConvWide & "Åo"
		Case "|"
			StrConvWide = StrConvWide & "Åb"
		Case "}"
			StrConvWide = StrConvWide & "Åp"
		Case "~"
			StrConvWide = StrConvWide & "Å`"
		Case "°"
			StrConvWide = StrConvWide & "ÅB"
		Case "¢"
			StrConvWide = StrConvWide & "Åu"
		Case "£"
			StrConvWide = StrConvWide & "Åv"
		Case "§"
			StrConvWide = StrConvWide & "ÅA"
		Case "•"
			StrConvWide = StrConvWide & "ÅE"
		Case "¶"
			StrConvWide = StrConvWide & "Éí"
		Case "ß"
			StrConvWide = StrConvWide & "É@"
		Case "®"
			StrConvWide = StrConvWide & "ÉB"
		Case "©"
			StrConvWide = StrConvWide & "ÉD"
		Case "™"
			StrConvWide = StrConvWide & "ÉF"
		Case "´"
			StrConvWide = StrConvWide & "ÉH"
		Case "¨"
			StrConvWide = StrConvWide & "ÉÉ"
		Case "≠"
			StrConvWide = StrConvWide & "ÉÖ"
		Case "Æ"
			StrConvWide = StrConvWide & "Éá"
		Case "Ø"
			StrConvWide = StrConvWide & "Éb"
		Case "∞"
			StrConvWide = StrConvWide & "Å["
		Case "±"
			StrConvWide = StrConvWide & "ÉA"
		Case "≤"
			StrConvWide = StrConvWide & "ÉC"
		Case "≥"
			StrConvWide = StrConvWide & "ÉE"
		Case "≥ﬁ"
			StrConvWide = StrConvWide & "Éî"
		Case "¥"
			StrConvWide = StrConvWide & "ÉG"
		Case "µ"
			StrConvWide = StrConvWide & "ÉI"
		Case "∂"
			StrConvWide = StrConvWide & "ÉJ"
		Case "∂ﬁ"
			StrConvWide = StrConvWide & "ÉK"
		Case "∑"
			StrConvWide = StrConvWide & "ÉL"
		Case "∑ﬁ"
			StrConvWide = StrConvWide & "ÉM"
		Case "∏"
			StrConvWide = StrConvWide & "ÉN"
		Case "∏ﬁ"
			StrConvWide = StrConvWide & "ÉO"
		Case "π"
			StrConvWide = StrConvWide & "ÉP"
		Case "πﬁ"
			StrConvWide = StrConvWide & "ÉQ"
		Case "∫"
			StrConvWide = StrConvWide & "ÉR"
		Case "∫ﬁ"
			StrConvWide = StrConvWide & "ÉS"
		Case "ª"
			StrConvWide = StrConvWide & "ÉT"
		Case "ªﬁ"
			StrConvWide = StrConvWide & "ÉU"
		Case "º"
			StrConvWide = StrConvWide & "ÉV"
		Case "ºﬁ"
			StrConvWide = StrConvWide & "ÉW"
		Case "Ω"
			StrConvWide = StrConvWide & "ÉX"
		Case "Ωﬁ"
			StrConvWide = StrConvWide & "ÉY"
		Case "æ"
			StrConvWide = StrConvWide & "ÉZ"
		Case "æﬁ"
			StrConvWide = StrConvWide & "É["
		Case "ø"
			StrConvWide = StrConvWide & "É\"
		Case "øﬁ"
			StrConvWide = StrConvWide & "É]"
		Case "¿"
			StrConvWide = StrConvWide & "É^"
		Case "¿ﬁ"
			StrConvWide = StrConvWide & "É_"
		Case "¡"
			StrConvWide = StrConvWide & "É`"
		Case "¡ﬁ"
			StrConvWide = StrConvWide & "Éa"
		Case "¬"
			StrConvWide = StrConvWide & "Éc"
		Case "¬ﬁ"
			StrConvWide = StrConvWide & "Éd"
		Case "√"
			StrConvWide = StrConvWide & "Ée"
		Case "√ﬁ"
			StrConvWide = StrConvWide & "Éf"
		Case "ƒ"
			StrConvWide = StrConvWide & "Ég"
		Case "ƒﬁ"
			StrConvWide = StrConvWide & "Éh"
		Case "≈"
			StrConvWide = StrConvWide & "Éi"
		Case "∆"
			StrConvWide = StrConvWide & "Éj"
		Case "«"
			StrConvWide = StrConvWide & "Ék"
		Case "»"
			StrConvWide = StrConvWide & "Él"
		Case "…"
			StrConvWide = StrConvWide & "Ém"
		Case " "
			StrConvWide = StrConvWide & "Én"
		Case " ﬁ"
			StrConvWide = StrConvWide & "Éo"
		Case " ﬂ"
			StrConvWide = StrConvWide & "Ép"
		Case "À"
			StrConvWide = StrConvWide & "Éq"
		Case "Àﬁ"
			StrConvWide = StrConvWide & "Ér"
		Case "Àﬂ"
			StrConvWide = StrConvWide & "És"
		Case "Ã"
			StrConvWide = StrConvWide & "Ét"
		Case "Ãﬁ"
			StrConvWide = StrConvWide & "Éu"
		Case "Ãﬂ"
			StrConvWide = StrConvWide & "Év"
		Case "Õ"
			StrConvWide = StrConvWide & "Éw"
		Case "Õﬁ"
			StrConvWide = StrConvWide & "Éx"
		Case "Õﬂ"
			StrConvWide = StrConvWide & "Éy"
		Case "Œ"
			StrConvWide = StrConvWide & "Éz"
		Case "Œﬁ"
			StrConvWide = StrConvWide & "É{"
		Case "Œﬂ"
			StrConvWide = StrConvWide & "É|"
		Case "œ"
			StrConvWide = StrConvWide & "É}"
		Case "–"
			StrConvWide = StrConvWide & "É~"
		Case "—"
			StrConvWide = StrConvWide & "ÉÄ"
		Case "“"
			StrConvWide = StrConvWide & "ÉÅ"
		Case "”"
			StrConvWide = StrConvWide & "ÉÇ"
		Case "‘"
			StrConvWide = StrConvWide & "ÉÑ"
		Case "’"
			StrConvWide = StrConvWide & "ÉÜ"
		Case "÷"
			StrConvWide = StrConvWide & "Éà"
		Case "◊"
			StrConvWide = StrConvWide & "Éâ"
		Case "ÿ"
			StrConvWide = StrConvWide & "Éä"
		Case "Ÿ"
			StrConvWide = StrConvWide & "Éã"
		Case "⁄"
			StrConvWide = StrConvWide & "Éå"
		Case "€"
			StrConvWide = StrConvWide & "Éç"
		Case "‹"
			StrConvWide = StrConvWide & "Éè"
		Case "›"
			StrConvWide = StrConvWide & "Éì"
		Case "ﬁ"
			StrConvWide = StrConvWide & "ÅJ"
		Case "ﬂ"
			StrConvWide = StrConvWide & "ÅK"
		Case " "
			StrConvWide = StrConvWide & "Å@"
		Case "!"
			StrConvWide = StrConvWide & "ÅI"
		Case """"
			StrConvWide = StrConvWide & "˙W"
		Case "#"
			StrConvWide = StrConvWide & "Åî"
		Case "$"
			StrConvWide = StrConvWide & "Åê"
		Case "%"
			StrConvWide = StrConvWide & "Åì"
		Case "&"
			StrConvWide = StrConvWide & "Åï"
		Case "'"
			StrConvWide = StrConvWide & "˙V"
		Case "("
			StrConvWide = StrConvWide & "Åi"
		Case ")"
			StrConvWide = StrConvWide & "Åj"
		Case "*"
			StrConvWide = StrConvWide & "Åñ"
		Case "+"
			StrConvWide = StrConvWide & "Å{"
		Case ","
			StrConvWide = StrConvWide & "ÅC"
		Case "-"
			StrConvWide = StrConvWide & "Å|"
		Case "."
			StrConvWide = StrConvWide & "ÅD"
		Case "/"
			StrConvWide = StrConvWide & "Å^"
		Case "0"
			StrConvWide = StrConvWide & "ÇO"
		Case "1"
			StrConvWide = StrConvWide & "ÇP"
		Case "2"
			StrConvWide = StrConvWide & "ÇQ"
		Case "3"
			StrConvWide = StrConvWide & "ÇR"
		Case "4"
			StrConvWide = StrConvWide & "ÇS"
		Case "5"
			StrConvWide = StrConvWide & "ÇT"
		Case "6"
			StrConvWide = StrConvWide & "ÇU"
		Case "7"
			StrConvWide = StrConvWide & "ÇV"
		Case "8"
			StrConvWide = StrConvWide & "ÇW"
		Case "9"
			StrConvWide = StrConvWide & "ÇX"
		Case ":"
			StrConvWide = StrConvWide & "ÅF"
		Case ";"
			StrConvWide = StrConvWide & "ÅG"
		Case "<"
			StrConvWide = StrConvWide & "ÅÉ"
		Case "="
			StrConvWide = StrConvWide & "ÅÅ"
		Case ">"
			StrConvWide = StrConvWide & "ÅÑ"
		Case "?"
			StrConvWide = StrConvWide & "ÅH"
		Case "@"
			StrConvWide = StrConvWide & "Åó"
		Case "A"
			StrConvWide = StrConvWide & "Ç`"
		Case "B"
			StrConvWide = StrConvWide & "Ça"
		Case "C"
			StrConvWide = StrConvWide & "Çb"
		Case "D"
			StrConvWide = StrConvWide & "Çc"
		Case "E"
			StrConvWide = StrConvWide & "Çd"
		Case "F"
			StrConvWide = StrConvWide & "Çe"
		Case "G"
			StrConvWide = StrConvWide & "Çf"
		Case "H"
			StrConvWide = StrConvWide & "Çg"
		Case "I"
			StrConvWide = StrConvWide & "Çh"
		Case "J"
			StrConvWide = StrConvWide & "Çi"
		Case "K"
			StrConvWide = StrConvWide & "Çj"
		Case "L"
			StrConvWide = StrConvWide & "Çk"
		Case "M"
			StrConvWide = StrConvWide & "Çl"
		Case "N"
			StrConvWide = StrConvWide & "Çm"
		Case "O"
			StrConvWide = StrConvWide & "Çn"
		Case "P"
			StrConvWide = StrConvWide & "Ço"
		Case "Q"
			StrConvWide = StrConvWide & "Çp"
		Case "R"
			StrConvWide = StrConvWide & "Çq"
		Case "S"
			StrConvWide = StrConvWide & "Çr"
		Case "T"
			StrConvWide = StrConvWide & "Çs"
		Case "U"
			StrConvWide = StrConvWide & "Çt"
		Case "V"
			StrConvWide = StrConvWide & "Çu"
		Case "W"
			StrConvWide = StrConvWide & "Çv"
		Case "X"
			StrConvWide = StrConvWide & "Çw"
		Case "Y"
			StrConvWide = StrConvWide & "Çx"
		Case "Z"
			StrConvWide = StrConvWide & "Çy"
		Case "["
			StrConvWide = StrConvWide & "Åm"
		Case "]"
			StrConvWide = StrConvWide & "Ån"
		Case "^"
			StrConvWide = StrConvWide & "ÅO"
		Case "_"
			StrConvWide = StrConvWide & "ÅQ"
		Case "`"
			StrConvWide = StrConvWide & "ÅM"
		Case "a"
			StrConvWide = StrConvWide & "ÇÅ"
		Case "b"
			StrConvWide = StrConvWide & "ÇÇ"
		Case "c"
			StrConvWide = StrConvWide & "ÇÉ"
		Case "d"
			StrConvWide = StrConvWide & "ÇÑ"
		Case "e"
			StrConvWide = StrConvWide & "ÇÖ"
		Case "f"
			StrConvWide = StrConvWide & "ÇÜ"
		Case "g"
			StrConvWide = StrConvWide & "Çá"
		Case "h"
			StrConvWide = StrConvWide & "Çà"
		Case "i"
			StrConvWide = StrConvWide & "Çâ"
		Case "j"
			StrConvWide = StrConvWide & "Çä"
		Case "k"
			StrConvWide = StrConvWide & "Çã"
		Case "l"
			StrConvWide = StrConvWide & "Çå"
		Case "m"
			StrConvWide = StrConvWide & "Çç"
		Case "n"
			StrConvWide = StrConvWide & "Çé"
		Case "o"
			StrConvWide = StrConvWide & "Çè"
		Case "p"
			StrConvWide = StrConvWide & "Çê"
		Case "q"
			StrConvWide = StrConvWide & "Çë"
		Case "r"
			StrConvWide = StrConvWide & "Çí"
		Case "s"
			StrConvWide = StrConvWide & "Çì"
		Case "t"
			StrConvWide = StrConvWide & "Çî"
		Case "u"
			StrConvWide = StrConvWide & "Çï"
		Case "v"
			StrConvWide = StrConvWide & "Çñ"
		Case "w"
			StrConvWide = StrConvWide & "Çó"
		Case "x"
			StrConvWide = StrConvWide & "Çò"
		Case "y"
			StrConvWide = StrConvWide & "Çô"
		Case "z"
			StrConvWide = StrConvWide & "Çö"
		Case "{"
			StrConvWide = StrConvWide & "Åo"
		Case "|"
			StrConvWide = StrConvWide & "Åb"
		Case "}"
			StrConvWide = StrConvWide & "Åp"
		Case "~"
			StrConvWide = StrConvWide & "Å`"
		Case "Ç§ﬁ"
			StrConvWide = StrConvWide & "Éî"
		Case "Ç©ﬁ"
			StrConvWide = StrConvWide & "Ç™"
		Case "Ç´ﬁ"
			StrConvWide = StrConvWide & "Ç¨"
		Case "Ç≠ﬁ"
			StrConvWide = StrConvWide & "ÇÆ"
		Case "ÇØﬁ"
			StrConvWide = StrConvWide & "Ç∞"
		Case "Ç±ﬁ"
			StrConvWide = StrConvWide & "Ç≤"
		Case "Ç≥ﬁ"
			StrConvWide = StrConvWide & "Ç¥"
		Case "Çµﬁ"
			StrConvWide = StrConvWide & "Ç∂"
		Case "Ç∑ﬁ"
			StrConvWide = StrConvWide & "Ç∏"
		Case "Çπﬁ"
			StrConvWide = StrConvWide & "Ç∫"
		Case "Çªﬁ"
			StrConvWide = StrConvWide & "Çº"
		Case "ÇΩﬁ"
			StrConvWide = StrConvWide & "Çæ"
		Case "Çøﬁ"
			StrConvWide = StrConvWide & "Ç¿"
		Case "Ç¬ﬁ"
			StrConvWide = StrConvWide & "Ç√"
		Case "Çƒﬁ"
			StrConvWide = StrConvWide & "Ç≈"
		Case "Ç∆ﬁ"
			StrConvWide = StrConvWide & "Ç«"
		Case "ÇÕﬁ"
			StrConvWide = StrConvWide & "ÇŒ"
		Case "ÇÕﬂ"
			StrConvWide = StrConvWide & "Çœ"
		Case "Ç–ﬁ"
			StrConvWide = StrConvWide & "Ç—"
		Case "Ç–ﬂ"
			StrConvWide = StrConvWide & "Ç“"
		Case "Ç”ﬁ"
			StrConvWide = StrConvWide & "Ç‘"
		Case "Ç”ﬂ"
			StrConvWide = StrConvWide & "Ç’"
		Case "Ç÷ﬁ"
			StrConvWide = StrConvWide & "Ç◊"
		Case "Ç÷ﬂ"
			StrConvWide = StrConvWide & "Çÿ"
		Case "ÇŸﬁ"
			StrConvWide = StrConvWide & "Ç⁄"
		Case "ÇŸﬂ"
			StrConvWide = StrConvWide & "Ç€"
		Case "ÉEﬁ"
			StrConvWide = StrConvWide & "Éî"
		Case "ÉJﬁ"
			StrConvWide = StrConvWide & "ÉK"
		Case "ÉLﬁ"
			StrConvWide = StrConvWide & "ÉM"
		Case "ÉNﬁ"
			StrConvWide = StrConvWide & "ÉO"
		Case "ÉPﬁ"
			StrConvWide = StrConvWide & "ÉQ"
		Case "ÉRﬁ"
			StrConvWide = StrConvWide & "ÉS"
		Case "ÉTﬁ"
			StrConvWide = StrConvWide & "ÉU"
		Case "ÉVﬁ"
			StrConvWide = StrConvWide & "ÉW"
		Case "ÉXﬁ"
			StrConvWide = StrConvWide & "ÉY"
		Case "ÉZﬁ"
			StrConvWide = StrConvWide & "É["
		Case "É\ﬁ"
			StrConvWide = StrConvWide & "É]"
		Case "É^ﬁ"
			StrConvWide = StrConvWide & "É_"
		Case "É`ﬁ"
			StrConvWide = StrConvWide & "Éa"
		Case "Écﬁ"
			StrConvWide = StrConvWide & "Éd"
		Case "Éeﬁ"
			StrConvWide = StrConvWide & "Éf"
		Case "Égﬁ"
			StrConvWide = StrConvWide & "Éh"
		Case "Énﬁ"
			StrConvWide = StrConvWide & "Éo"
		Case "Énﬂ"
			StrConvWide = StrConvWide & "Ép"
		Case "Éqﬁ"
			StrConvWide = StrConvWide & "Ér"
		Case "Éqﬂ"
			StrConvWide = StrConvWide & "És"
		Case "Étﬁ"
			StrConvWide = StrConvWide & "Éu"
		Case "Étﬂ"
			StrConvWide = StrConvWide & "Év"
		Case "Éwﬁ"
			StrConvWide = StrConvWide & "Éx"
		Case "Éwﬂ"
			StrConvWide = StrConvWide & "Éy"
		Case "Ézﬁ"
			StrConvWide = StrConvWide & "É{"
		Case "Ézﬂ"
			StrConvWide = StrConvWide & "É|"
		Case "°"
			StrConvWide = StrConvWide & "ÅB"
		Case "¢"
			StrConvWide = StrConvWide & "Åu"
		Case "£"
			StrConvWide = StrConvWide & "Åv"
		Case "§"
			StrConvWide = StrConvWide & "ÅA"
		Case "•"
			StrConvWide = StrConvWide & "ÅE"
		Case "¶"
			StrConvWide = StrConvWide & "Éí"
		Case "ß"
			StrConvWide = StrConvWide & "É@"
		Case "®"
			StrConvWide = StrConvWide & "ÉB"
		Case "©"
			StrConvWide = StrConvWide & "ÉD"
		Case "™"
			StrConvWide = StrConvWide & "ÉF"
		Case "´"
			StrConvWide = StrConvWide & "ÉH"
		Case "¨"
			StrConvWide = StrConvWide & "ÉÉ"
		Case "≠"
			StrConvWide = StrConvWide & "ÉÖ"
		Case "Æ"
			StrConvWide = StrConvWide & "Éá"
		Case "Ø"
			StrConvWide = StrConvWide & "Éb"
		Case "∞"
			StrConvWide = StrConvWide & "Å["
		Case "±"
			StrConvWide = StrConvWide & "ÉA"
		Case "≤"
			StrConvWide = StrConvWide & "ÉC"
		Case "≥"
			StrConvWide = StrConvWide & "ÉE"
		Case "≥ﬁ"
			StrConvWide = StrConvWide & "Éî"
		Case "¥"
			StrConvWide = StrConvWide & "ÉG"
		Case "µ"
			StrConvWide = StrConvWide & "ÉI"
		Case "∂"
			StrConvWide = StrConvWide & "ÉJ"
		Case "∂ﬁ"
			StrConvWide = StrConvWide & "ÉK"
		Case "∑"
			StrConvWide = StrConvWide & "ÉL"
		Case "∑ﬁ"
			StrConvWide = StrConvWide & "ÉM"
		Case "∏"
			StrConvWide = StrConvWide & "ÉN"
		Case "∏ﬁ"
			StrConvWide = StrConvWide & "ÉO"
		Case "π"
			StrConvWide = StrConvWide & "ÉP"
		Case "πﬁ"
			StrConvWide = StrConvWide & "ÉQ"
		Case "∫"
			StrConvWide = StrConvWide & "ÉR"
		Case "∫ﬁ"
			StrConvWide = StrConvWide & "ÉS"
		Case "ª"
			StrConvWide = StrConvWide & "ÉT"
		Case "ªﬁ"
			StrConvWide = StrConvWide & "ÉU"
		Case "º"
			StrConvWide = StrConvWide & "ÉV"
		Case "ºﬁ"
			StrConvWide = StrConvWide & "ÉW"
		Case "Ω"
			StrConvWide = StrConvWide & "ÉX"
		Case "Ωﬁ"
			StrConvWide = StrConvWide & "ÉY"
		Case "æ"
			StrConvWide = StrConvWide & "ÉZ"
		Case "æﬁ"
			StrConvWide = StrConvWide & "É["
		Case "ø"
			StrConvWide = StrConvWide & "É\"
		Case "øﬁ"
			StrConvWide = StrConvWide & "É]"
		Case "¿"
			StrConvWide = StrConvWide & "É^"
		Case "¿ﬁ"
			StrConvWide = StrConvWide & "É_"
		Case "¡"
			StrConvWide = StrConvWide & "É`"
		Case "¡ﬁ"
			StrConvWide = StrConvWide & "Éa"
		Case "¬"
			StrConvWide = StrConvWide & "Éc"
		Case "¬ﬁ"
			StrConvWide = StrConvWide & "Éd"
		Case "√"
			StrConvWide = StrConvWide & "Ée"
		Case "√ﬁ"
			StrConvWide = StrConvWide & "Éf"
		Case "ƒ"
			StrConvWide = StrConvWide & "Ég"
		Case "ƒﬁ"
			StrConvWide = StrConvWide & "Éh"
		Case "≈"
			StrConvWide = StrConvWide & "Éi"
		Case "∆"
			StrConvWide = StrConvWide & "Éj"
		Case "«"
			StrConvWide = StrConvWide & "Ék"
		Case "»"
			StrConvWide = StrConvWide & "Él"
		Case "…"
			StrConvWide = StrConvWide & "Ém"
		Case " "
			StrConvWide = StrConvWide & "Én"
		Case " ﬁ"
			StrConvWide = StrConvWide & "Éo"
		Case " ﬂ"
			StrConvWide = StrConvWide & "Ép"
		Case "À"
			StrConvWide = StrConvWide & "Éq"
		Case "Àﬁ"
			StrConvWide = StrConvWide & "Ér"
		Case "Àﬂ"
			StrConvWide = StrConvWide & "És"
		Case "Ã"
			StrConvWide = StrConvWide & "Ét"
		Case "Ãﬁ"
			StrConvWide = StrConvWide & "Éu"
		Case "Ãﬂ"
			StrConvWide = StrConvWide & "Év"
		Case "Õ"
			StrConvWide = StrConvWide & "Éw"
		Case "Õﬁ"
			StrConvWide = StrConvWide & "Éx"
		Case "Õﬂ"
			StrConvWide = StrConvWide & "Éy"
		Case "Œ"
			StrConvWide = StrConvWide & "Éz"
		Case "Œﬁ"
			StrConvWide = StrConvWide & "É{"
		Case "Œﬂ"
			StrConvWide = StrConvWide & "É|"
		Case "œ"
			StrConvWide = StrConvWide & "É}"
		Case "–"
			StrConvWide = StrConvWide & "É~"
		Case "—"
			StrConvWide = StrConvWide & "ÉÄ"
		Case "“"
			StrConvWide = StrConvWide & "ÉÅ"
		Case "”"
			StrConvWide = StrConvWide & "ÉÇ"
		Case "‘"
			StrConvWide = StrConvWide & "ÉÑ"
		Case "’"
			StrConvWide = StrConvWide & "ÉÜ"
		Case "÷"
			StrConvWide = StrConvWide & "Éà"
		Case "◊"
			StrConvWide = StrConvWide & "Éâ"
		Case "ÿ"
			StrConvWide = StrConvWide & "Éä"
		Case "Ÿ"
			StrConvWide = StrConvWide & "Éã"
		Case "⁄"
			StrConvWide = StrConvWide & "Éå"
		Case "€"
			StrConvWide = StrConvWide & "Éç"
		Case "‹"
			StrConvWide = StrConvWide & "Éè"
		Case "›"
			StrConvWide = StrConvWide & "Éì"
		Case "ﬁ"
			StrConvWide = StrConvWide & "ÅJ"
		Case "ﬂ"
			StrConvWide = StrConvWide & "ÅK"
		Case Else
			StrConvWide = StrConvWide & sChr
		End Select
	Next
End Function

'***************************************************
' StrConvNarrow
'---------------------------------------------------
' ópìr : StrConv(s,vbNarrow) ÇÃÉNÉçÅ[Éì
' à¯êî : ïœä∑Ç∑ÇÈï∂éöóÒ
' ñﬂíl : ïœä∑Ç≥ÇÍÇΩï∂éöóÒ
'***************************************************
Function StrConvNarrow(s)
	Dim nCnt
	Dim nLen
	Dim sChr
	Dim sMud

	nLen = Len(s)
	For nCnt = 1 To nLen
		sChr = Mid(s,nCnt,1)
		sMud = Mid(s,nCnt+1,1) 
		If InStr("ﬁﬂ", sMud) Then
			sChr = sChr & sMud
			nCnt = nCnt + 1
		End If
		Select Case sChr
		Case "ÅE"
			StrConvNarrow = StrConvNarrow & "•"
		Case "Å@"
			StrConvNarrow = StrConvNarrow & " "
		Case "ÅA"
			StrConvNarrow = StrConvNarrow & "§"
		Case "ÅB"
			StrConvNarrow = StrConvNarrow & "°"
		Case "ÅC"
			StrConvNarrow = StrConvNarrow & ","
		Case "ÅD"
			StrConvNarrow = StrConvNarrow & "."
		Case "ÅE"
			StrConvNarrow = StrConvNarrow & "•"
		Case "ÅF"
			StrConvNarrow = StrConvNarrow & ":"
		Case "ÅG"
			StrConvNarrow = StrConvNarrow & ";"
		Case "ÅH"
			StrConvNarrow = StrConvNarrow & "?"
		Case "ÅI"
			StrConvNarrow = StrConvNarrow & "!"
		Case "ÅJ"
			StrConvNarrow = StrConvNarrow & "ﬁ"
		Case "ÅK"
			StrConvNarrow = StrConvNarrow & "ﬂ"
		Case "ÅM"
			StrConvNarrow = StrConvNarrow & "`"
		Case "ÅO"
			StrConvNarrow = StrConvNarrow & "^"
		Case "ÅQ"
			StrConvNarrow = StrConvNarrow & "_"
		Case "Å["
			StrConvNarrow = StrConvNarrow & "∞"
		Case "Å^"
			StrConvNarrow = StrConvNarrow & "/"
		Case "Å`"
			StrConvNarrow = StrConvNarrow & "~"
		Case "Åb"
			StrConvNarrow = StrConvNarrow & "|"
		Case "Åe"
			StrConvNarrow = StrConvNarrow & "'"
		Case "Åf"
			StrConvNarrow = StrConvNarrow & "'"
		Case "Åg"
			StrConvNarrow = StrConvNarrow & """"
		Case "Åh"
			StrConvNarrow = StrConvNarrow & """"
		Case "Åi"
			StrConvNarrow = StrConvNarrow & "("
		Case "Åj"
			StrConvNarrow = StrConvNarrow & ")"
		Case "Åm"
			StrConvNarrow = StrConvNarrow & "["
		Case "Ån"
			StrConvNarrow = StrConvNarrow & "]"
		Case "Åo"
			StrConvNarrow = StrConvNarrow & "{"
		Case "Åp"
			StrConvNarrow = StrConvNarrow & "}"
		Case "Åu"
			StrConvNarrow = StrConvNarrow & "¢"
		Case "Åv"
			StrConvNarrow = StrConvNarrow & "£"
		Case "Å{"
			StrConvNarrow = StrConvNarrow & "+"
		Case "Å|"
			StrConvNarrow = StrConvNarrow & "-"
		Case "ÅE"
			StrConvNarrow = StrConvNarrow & "•"
		Case "ÅÅ"
			StrConvNarrow = StrConvNarrow & "="
		Case "ÅÉ"
			StrConvNarrow = StrConvNarrow & "<"
		Case "ÅÑ"
			StrConvNarrow = StrConvNarrow & ">"
		Case "Åè"
			StrConvNarrow = StrConvNarrow & "\"
		Case "Åê"
			StrConvNarrow = StrConvNarrow & "$"
		Case "Åì"
			StrConvNarrow = StrConvNarrow & "%"
		Case "Åî"
			StrConvNarrow = StrConvNarrow & "#"
		Case "Åï"
			StrConvNarrow = StrConvNarrow & "&"
		Case "Åñ"
			StrConvNarrow = StrConvNarrow & "*"
		Case "Åó"
			StrConvNarrow = StrConvNarrow & "@"
		Case "ÅE"
			StrConvNarrow = StrConvNarrow & "•"
		Case "ÇO"
			StrConvNarrow = StrConvNarrow & "0"
		Case "ÇP"
			StrConvNarrow = StrConvNarrow & "1"
		Case "ÇQ"
			StrConvNarrow = StrConvNarrow & "2"
		Case "ÇR"
			StrConvNarrow = StrConvNarrow & "3"
		Case "ÇS"
			StrConvNarrow = StrConvNarrow & "4"
		Case "ÇT"
			StrConvNarrow = StrConvNarrow & "5"
		Case "ÇU"
			StrConvNarrow = StrConvNarrow & "6"
		Case "ÇV"
			StrConvNarrow = StrConvNarrow & "7"
		Case "ÇW"
			StrConvNarrow = StrConvNarrow & "8"
		Case "ÇX"
			StrConvNarrow = StrConvNarrow & "9"
		Case "ÅE"
			StrConvNarrow = StrConvNarrow & "•"
		Case "Ç`"
			StrConvNarrow = StrConvNarrow & "A"
		Case "Ça"
			StrConvNarrow = StrConvNarrow & "B"
		Case "Çb"
			StrConvNarrow = StrConvNarrow & "C"
		Case "Çc"
			StrConvNarrow = StrConvNarrow & "D"
		Case "Çd"
			StrConvNarrow = StrConvNarrow & "E"
		Case "Çe"
			StrConvNarrow = StrConvNarrow & "F"
		Case "Çf"
			StrConvNarrow = StrConvNarrow & "G"
		Case "Çg"
			StrConvNarrow = StrConvNarrow & "H"
		Case "Çh"
			StrConvNarrow = StrConvNarrow & "I"
		Case "Çi"
			StrConvNarrow = StrConvNarrow & "J"
		Case "Çj"
			StrConvNarrow = StrConvNarrow & "K"
		Case "Çk"
			StrConvNarrow = StrConvNarrow & "L"
		Case "Çl"
			StrConvNarrow = StrConvNarrow & "M"
		Case "Çm"
			StrConvNarrow = StrConvNarrow & "N"
		Case "Çn"
			StrConvNarrow = StrConvNarrow & "O"
		Case "Ço"
			StrConvNarrow = StrConvNarrow & "P"
		Case "Çp"
			StrConvNarrow = StrConvNarrow & "Q"
		Case "Çq"
			StrConvNarrow = StrConvNarrow & "R"
		Case "Çr"
			StrConvNarrow = StrConvNarrow & "S"
		Case "Çs"
			StrConvNarrow = StrConvNarrow & "T"
		Case "Çt"
			StrConvNarrow = StrConvNarrow & "U"
		Case "Çu"
			StrConvNarrow = StrConvNarrow & "V"
		Case "Çv"
			StrConvNarrow = StrConvNarrow & "W"
		Case "Çw"
			StrConvNarrow = StrConvNarrow & "X"
		Case "Çx"
			StrConvNarrow = StrConvNarrow & "Y"
		Case "Çy"
			StrConvNarrow = StrConvNarrow & "Z"
		Case "ÅE"
			StrConvNarrow = StrConvNarrow & "•"
		Case "ÇÅ"
			StrConvNarrow = StrConvNarrow & "a"
		Case "ÇÇ"
			StrConvNarrow = StrConvNarrow & "b"
		Case "ÇÉ"
			StrConvNarrow = StrConvNarrow & "c"
		Case "ÇÑ"
			StrConvNarrow = StrConvNarrow & "d"
		Case "ÇÖ"
			StrConvNarrow = StrConvNarrow & "e"
		Case "ÇÜ"
			StrConvNarrow = StrConvNarrow & "f"
		Case "Çá"
			StrConvNarrow = StrConvNarrow & "g"
		Case "Çà"
			StrConvNarrow = StrConvNarrow & "h"
		Case "Çâ"
			StrConvNarrow = StrConvNarrow & "i"
		Case "Çä"
			StrConvNarrow = StrConvNarrow & "j"
		Case "Çã"
			StrConvNarrow = StrConvNarrow & "k"
		Case "Çå"
			StrConvNarrow = StrConvNarrow & "l"
		Case "Çç"
			StrConvNarrow = StrConvNarrow & "m"
		Case "Çé"
			StrConvNarrow = StrConvNarrow & "n"
		Case "Çè"
			StrConvNarrow = StrConvNarrow & "o"
		Case "Çê"
			StrConvNarrow = StrConvNarrow & "p"
		Case "Çë"
			StrConvNarrow = StrConvNarrow & "q"
		Case "Çí"
			StrConvNarrow = StrConvNarrow & "r"
		Case "Çì"
			StrConvNarrow = StrConvNarrow & "s"
		Case "Çî"
			StrConvNarrow = StrConvNarrow & "t"
		Case "Çï"
			StrConvNarrow = StrConvNarrow & "u"
		Case "Çñ"
			StrConvNarrow = StrConvNarrow & "v"
		Case "Çó"
			StrConvNarrow = StrConvNarrow & "w"
		Case "Çò"
			StrConvNarrow = StrConvNarrow & "x"
		Case "Çô"
			StrConvNarrow = StrConvNarrow & "y"
		Case "Çö"
			StrConvNarrow = StrConvNarrow & "z"
		Case "ÅE"
			StrConvNarrow = StrConvNarrow & "•"
		Case "É@"
			StrConvNarrow = StrConvNarrow & "ß"
		Case "ÉA"
			StrConvNarrow = StrConvNarrow & "±"
		Case "ÉB"
			StrConvNarrow = StrConvNarrow & "®"
		Case "ÉC"
			StrConvNarrow = StrConvNarrow & "≤"
		Case "ÉD"
			StrConvNarrow = StrConvNarrow & "©"
		Case "ÉE"
			StrConvNarrow = StrConvNarrow & "≥"
		Case "ÉF"
			StrConvNarrow = StrConvNarrow & "™"
		Case "ÉG"
			StrConvNarrow = StrConvNarrow & "¥"
		Case "ÉH"
			StrConvNarrow = StrConvNarrow & "´"
		Case "ÉI"
			StrConvNarrow = StrConvNarrow & "µ"
		Case "ÉJ"
			StrConvNarrow = StrConvNarrow & "∂"
		Case "ÉK"
			StrConvNarrow = StrConvNarrow & "∂ﬁ"
		Case "ÉL"
			StrConvNarrow = StrConvNarrow & "∑"
		Case "ÉM"
			StrConvNarrow = StrConvNarrow & "∑ﬁ"
		Case "ÉN"
			StrConvNarrow = StrConvNarrow & "∏"
		Case "ÉO"
			StrConvNarrow = StrConvNarrow & "∏ﬁ"
		Case "ÉP"
			StrConvNarrow = StrConvNarrow & "π"
		Case "ÉQ"
			StrConvNarrow = StrConvNarrow & "πﬁ"
		Case "ÉR"
			StrConvNarrow = StrConvNarrow & "∫"
		Case "ÉS"
			StrConvNarrow = StrConvNarrow & "∫ﬁ"
		Case "ÉT"
			StrConvNarrow = StrConvNarrow & "ª"
		Case "ÉU"
			StrConvNarrow = StrConvNarrow & "ªﬁ"
		Case "ÉV"
			StrConvNarrow = StrConvNarrow & "º"
		Case "ÉW"
			StrConvNarrow = StrConvNarrow & "ºﬁ"
		Case "ÉX"
			StrConvNarrow = StrConvNarrow & "Ω"
		Case "ÉY"
			StrConvNarrow = StrConvNarrow & "Ωﬁ"
		Case "ÉZ"
			StrConvNarrow = StrConvNarrow & "æ"
		Case "É["
			StrConvNarrow = StrConvNarrow & "æﬁ"
		Case "É\"
			StrConvNarrow = StrConvNarrow & "ø"
		Case "É]"
			StrConvNarrow = StrConvNarrow & "øﬁ"
		Case "É^"
			StrConvNarrow = StrConvNarrow & "¿"
		Case "É_"
			StrConvNarrow = StrConvNarrow & "¿ﬁ"
		Case "É`"
			StrConvNarrow = StrConvNarrow & "¡"
		Case "Éa"
			StrConvNarrow = StrConvNarrow & "¡ﬁ"
		Case "Éb"
			StrConvNarrow = StrConvNarrow & "Ø"
		Case "Éc"
			StrConvNarrow = StrConvNarrow & "¬"
		Case "Éd"
			StrConvNarrow = StrConvNarrow & "¬ﬁ"
		Case "Ée"
			StrConvNarrow = StrConvNarrow & "√"
		Case "Éf"
			StrConvNarrow = StrConvNarrow & "√ﬁ"
		Case "Ég"
			StrConvNarrow = StrConvNarrow & "ƒ"
		Case "Éh"
			StrConvNarrow = StrConvNarrow & "ƒﬁ"
		Case "Éi"
			StrConvNarrow = StrConvNarrow & "≈"
		Case "Éj"
			StrConvNarrow = StrConvNarrow & "∆"
		Case "Ék"
			StrConvNarrow = StrConvNarrow & "«"
		Case "Él"
			StrConvNarrow = StrConvNarrow & "»"
		Case "Ém"
			StrConvNarrow = StrConvNarrow & "…"
		Case "Én"
			StrConvNarrow = StrConvNarrow & " "
		Case "Éo"
			StrConvNarrow = StrConvNarrow & " ﬁ"
		Case "Ép"
			StrConvNarrow = StrConvNarrow & " ﬂ"
		Case "Éq"
			StrConvNarrow = StrConvNarrow & "À"
		Case "Ér"
			StrConvNarrow = StrConvNarrow & "Àﬁ"
		Case "És"
			StrConvNarrow = StrConvNarrow & "Àﬂ"
		Case "Ét"
			StrConvNarrow = StrConvNarrow & "Ã"
		Case "Éu"
			StrConvNarrow = StrConvNarrow & "Ãﬁ"
		Case "Év"
			StrConvNarrow = StrConvNarrow & "Ãﬂ"
		Case "Éw"
			StrConvNarrow = StrConvNarrow & "Õ"
		Case "Éx"
			StrConvNarrow = StrConvNarrow & "Õﬁ"
		Case "Éy"
			StrConvNarrow = StrConvNarrow & "Õﬂ"
		Case "Éz"
			StrConvNarrow = StrConvNarrow & "Œ"
		Case "É{"
			StrConvNarrow = StrConvNarrow & "Œﬁ"
		Case "É|"
			StrConvNarrow = StrConvNarrow & "Œﬂ"
		Case "É}"
			StrConvNarrow = StrConvNarrow & "œ"
		Case "É~"
			StrConvNarrow = StrConvNarrow & "–"
		Case "ÅE"
			StrConvNarrow = StrConvNarrow & "•"
		Case "ÉÄ"
			StrConvNarrow = StrConvNarrow & "—"
		Case "ÉÅ"
			StrConvNarrow = StrConvNarrow & "“"
		Case "ÉÇ"
			StrConvNarrow = StrConvNarrow & "”"
		Case "ÉÉ"
			StrConvNarrow = StrConvNarrow & "¨"
		Case "ÉÑ"
			StrConvNarrow = StrConvNarrow & "‘"
		Case "ÉÖ"
			StrConvNarrow = StrConvNarrow & "≠"
		Case "ÉÜ"
			StrConvNarrow = StrConvNarrow & "’"
		Case "Éá"
			StrConvNarrow = StrConvNarrow & "Æ"
		Case "Éà"
			StrConvNarrow = StrConvNarrow & "÷"
		Case "Éâ"
			StrConvNarrow = StrConvNarrow & "◊"
		Case "Éä"
			StrConvNarrow = StrConvNarrow & "ÿ"
		Case "Éã"
			StrConvNarrow = StrConvNarrow & "Ÿ"
		Case "Éå"
			StrConvNarrow = StrConvNarrow & "⁄"
		Case "Éç"
			StrConvNarrow = StrConvNarrow & "€"
		Case "Éè"
			StrConvNarrow = StrConvNarrow & "‹"
		Case "Éí"
			StrConvNarrow = StrConvNarrow & "¶"
		Case "Éì"
			StrConvNarrow = StrConvNarrow & "›"
		Case "Éî"
			StrConvNarrow = StrConvNarrow & "≥ﬁ"
		Case "ÅE"
			StrConvNarrow = StrConvNarrow & "•"
		Case "˙U"
			StrConvNarrow = StrConvNarrow & "|"
		Case "˙V"
			StrConvNarrow = StrConvNarrow & "'"
		Case "˙W"
			StrConvNarrow = StrConvNarrow & """"
		Case "ÅE"
			StrConvNarrow = StrConvNarrow & "•"
		Case "˙U"
			StrConvNarrow = StrConvNarrow & "|"
		Case "˙V"
			StrConvNarrow = StrConvNarrow & "'"
		Case "˙W"
			StrConvNarrow = StrConvNarrow & """"
		Case "ÅE"
			StrConvNarrow = StrConvNarrow & "•"
		Case Else
			StrConvNarrow = StrConvNarrow & sChr
		End Select
	Next
End Function

'***************************************************
' StrConvKatakana
'---------------------------------------------------
' ópìr : StrConv(s,vbKatakana) ÇÃÉNÉçÅ[Éì
' à¯êî : ïœä∑Ç∑ÇÈï∂éöóÒ
' ñﬂíl : ïœä∑Ç≥ÇÍÇΩï∂éöóÒ
'***************************************************
Function StrConvKatakana(s)
	Dim nCnt
	Dim nLen
	Dim sChr
	Dim sMud

	nLen = Len(s)
	For nCnt = 1 To nLen
		sChr = Mid(s,nCnt,1)
		sMud = Mid(s,nCnt+1,1) 
		If InStr("ﬁﬂ", sMud) Then
			sChr = sChr & sMud
			nCnt = nCnt + 1
		End If
		Select Case sChr
		Case "ÅT"
			StrConvKatakana = StrConvKatakana & "ÅR"
		Case "ÅU"
			StrConvKatakana = StrConvKatakana & "ÅS"
		Case "Çü"
			StrConvKatakana = StrConvKatakana & "É@"
		Case "Ç†"
			StrConvKatakana = StrConvKatakana & "ÉA"
		Case "Ç°"
			StrConvKatakana = StrConvKatakana & "ÉB"
		Case "Ç¢"
			StrConvKatakana = StrConvKatakana & "ÉC"
		Case "Ç£"
			StrConvKatakana = StrConvKatakana & "ÉD"
		Case "Ç§"
			StrConvKatakana = StrConvKatakana & "ÉE"
		Case "Ç•"
			StrConvKatakana = StrConvKatakana & "ÉF"
		Case "Ç¶"
			StrConvKatakana = StrConvKatakana & "ÉG"
		Case "Çß"
			StrConvKatakana = StrConvKatakana & "ÉH"
		Case "Ç®"
			StrConvKatakana = StrConvKatakana & "ÉI"
		Case "Ç©"
			StrConvKatakana = StrConvKatakana & "ÉJ"
		Case "Ç™"
			StrConvKatakana = StrConvKatakana & "ÉK"
		Case "Ç´"
			StrConvKatakana = StrConvKatakana & "ÉL"
		Case "Ç¨"
			StrConvKatakana = StrConvKatakana & "ÉM"
		Case "Ç≠"
			StrConvKatakana = StrConvKatakana & "ÉN"
		Case "ÇÆ"
			StrConvKatakana = StrConvKatakana & "ÉO"
		Case "ÇØ"
			StrConvKatakana = StrConvKatakana & "ÉP"
		Case "Ç∞"
			StrConvKatakana = StrConvKatakana & "ÉQ"
		Case "Ç±"
			StrConvKatakana = StrConvKatakana & "ÉR"
		Case "Ç≤"
			StrConvKatakana = StrConvKatakana & "ÉS"
		Case "Ç≥"
			StrConvKatakana = StrConvKatakana & "ÉT"
		Case "Ç¥"
			StrConvKatakana = StrConvKatakana & "ÉU"
		Case "Çµ"
			StrConvKatakana = StrConvKatakana & "ÉV"
		Case "Ç∂"
			StrConvKatakana = StrConvKatakana & "ÉW"
		Case "Ç∑"
			StrConvKatakana = StrConvKatakana & "ÉX"
		Case "Ç∏"
			StrConvKatakana = StrConvKatakana & "ÉY"
		Case "Çπ"
			StrConvKatakana = StrConvKatakana & "ÉZ"
		Case "Ç∫"
			StrConvKatakana = StrConvKatakana & "É["
		Case "Çª"
			StrConvKatakana = StrConvKatakana & "É\"
		Case "Çº"
			StrConvKatakana = StrConvKatakana & "É]"
		Case "ÇΩ"
			StrConvKatakana = StrConvKatakana & "É^"
		Case "Çæ"
			StrConvKatakana = StrConvKatakana & "É_"
		Case "Çø"
			StrConvKatakana = StrConvKatakana & "É`"
		Case "Ç¿"
			StrConvKatakana = StrConvKatakana & "Éa"
		Case "Ç¡"
			StrConvKatakana = StrConvKatakana & "Éb"
		Case "Ç¬"
			StrConvKatakana = StrConvKatakana & "Éc"
		Case "Ç√"
			StrConvKatakana = StrConvKatakana & "Éd"
		Case "Çƒ"
			StrConvKatakana = StrConvKatakana & "Ée"
		Case "Ç≈"
			StrConvKatakana = StrConvKatakana & "Éf"
		Case "Ç∆"
			StrConvKatakana = StrConvKatakana & "Ég"
		Case "Ç«"
			StrConvKatakana = StrConvKatakana & "Éh"
		Case "Ç»"
			StrConvKatakana = StrConvKatakana & "Éi"
		Case "Ç…"
			StrConvKatakana = StrConvKatakana & "Éj"
		Case "Ç "
			StrConvKatakana = StrConvKatakana & "Ék"
		Case "ÇÀ"
			StrConvKatakana = StrConvKatakana & "Él"
		Case "ÇÃ"
			StrConvKatakana = StrConvKatakana & "Ém"
		Case "ÇÕ"
			StrConvKatakana = StrConvKatakana & "Én"
		Case "ÇŒ"
			StrConvKatakana = StrConvKatakana & "Éo"
		Case "Çœ"
			StrConvKatakana = StrConvKatakana & "Ép"
		Case "Ç–"
			StrConvKatakana = StrConvKatakana & "Éq"
		Case "Ç—"
			StrConvKatakana = StrConvKatakana & "Ér"
		Case "Ç“"
			StrConvKatakana = StrConvKatakana & "És"
		Case "Ç”"
			StrConvKatakana = StrConvKatakana & "Ét"
		Case "Ç‘"
			StrConvKatakana = StrConvKatakana & "Éu"
		Case "Ç’"
			StrConvKatakana = StrConvKatakana & "Év"
		Case "Ç÷"
			StrConvKatakana = StrConvKatakana & "Éw"
		Case "Ç◊"
			StrConvKatakana = StrConvKatakana & "Éx"
		Case "Çÿ"
			StrConvKatakana = StrConvKatakana & "Éy"
		Case "ÇŸ"
			StrConvKatakana = StrConvKatakana & "Éz"
		Case "Ç⁄"
			StrConvKatakana = StrConvKatakana & "É{"
		Case "Ç€"
			StrConvKatakana = StrConvKatakana & "É|"
		Case "Ç‹"
			StrConvKatakana = StrConvKatakana & "É}"
		Case "Ç›"
			StrConvKatakana = StrConvKatakana & "É~"
		Case "Çﬁ"
			StrConvKatakana = StrConvKatakana & "ÉÄ"
		Case "Çﬂ"
			StrConvKatakana = StrConvKatakana & "ÉÅ"
		Case "Ç‡"
			StrConvKatakana = StrConvKatakana & "ÉÇ"
		Case "Ç·"
			StrConvKatakana = StrConvKatakana & "ÉÉ"
		Case "Ç‚"
			StrConvKatakana = StrConvKatakana & "ÉÑ"
		Case "Ç„"
			StrConvKatakana = StrConvKatakana & "ÉÖ"
		Case "Ç‰"
			StrConvKatakana = StrConvKatakana & "ÉÜ"
		Case "ÇÂ"
			StrConvKatakana = StrConvKatakana & "Éá"
		Case "ÇÊ"
			StrConvKatakana = StrConvKatakana & "Éà"
		Case "ÇÁ"
			StrConvKatakana = StrConvKatakana & "Éâ"
		Case "ÇË"
			StrConvKatakana = StrConvKatakana & "Éä"
		Case "ÇÈ"
			StrConvKatakana = StrConvKatakana & "Éã"
		Case "ÇÍ"
			StrConvKatakana = StrConvKatakana & "Éå"
		Case "ÇÎ"
			StrConvKatakana = StrConvKatakana & "Éç"
		Case "ÇÏ"
			StrConvKatakana = StrConvKatakana & "Éé"
		Case "ÇÌ"
			StrConvKatakana = StrConvKatakana & "Éè"
		Case "ÇÓ"
			StrConvKatakana = StrConvKatakana & "Éê"
		Case "ÇÔ"
			StrConvKatakana = StrConvKatakana & "Éë"
		Case "Ç"
			StrConvKatakana = StrConvKatakana & "Éí"
		Case "ÇÒ"
			StrConvKatakana = StrConvKatakana & "Éì"
		Case Else
			StrConvKatakana = StrConvKatakana & sChr
		End Select
	Next
End Function

'***************************************************
' StrConvHiragana
'---------------------------------------------------
' ópìr : StrConv(s,vbHiragana) ÇÃÉNÉçÅ[Éì
' à¯êî : ïœä∑Ç∑ÇÈï∂éöóÒ
' ñﬂíl : ïœä∑Ç≥ÇÍÇΩï∂éöóÒ
'***************************************************
Function StrConvHiragana(s)
	Dim nCnt
	Dim nLen
	Dim sChr
	Dim sMud

	nLen = Len(s)
	For nCnt = 1 To nLen
		sChr = Mid(s,nCnt,1)
		sMud = Mid(s,nCnt+1,1) 
		If InStr("ﬁﬂ", sMud) Then
			sChr = sChr & sMud
			nCnt = nCnt + 1
		End If
		Select Case sChr
		Case "ÅR"
			StrConvHiragana = StrConvHiragana & "ÅT"
		Case "ÅS"
			StrConvHiragana = StrConvHiragana & "ÅU"
		Case "É@"
			StrConvHiragana = StrConvHiragana & "Çü"
		Case "ÉA"
			StrConvHiragana = StrConvHiragana & "Ç†"
		Case "ÉB"
			StrConvHiragana = StrConvHiragana & "Ç°"
		Case "ÉC"
			StrConvHiragana = StrConvHiragana & "Ç¢"
		Case "ÉD"
			StrConvHiragana = StrConvHiragana & "Ç£"
		Case "ÉE"
			StrConvHiragana = StrConvHiragana & "Ç§"
		Case "ÉF"
			StrConvHiragana = StrConvHiragana & "Ç•"
		Case "ÉG"
			StrConvHiragana = StrConvHiragana & "Ç¶"
		Case "ÉH"
			StrConvHiragana = StrConvHiragana & "Çß"
		Case "ÉI"
			StrConvHiragana = StrConvHiragana & "Ç®"
		Case "ÉJ"
			StrConvHiragana = StrConvHiragana & "Ç©"
		Case "ÉK"
			StrConvHiragana = StrConvHiragana & "Ç™"
		Case "ÉL"
			StrConvHiragana = StrConvHiragana & "Ç´"
		Case "ÉM"
			StrConvHiragana = StrConvHiragana & "Ç¨"
		Case "ÉN"
			StrConvHiragana = StrConvHiragana & "Ç≠"
		Case "ÉO"
			StrConvHiragana = StrConvHiragana & "ÇÆ"
		Case "ÉP"
			StrConvHiragana = StrConvHiragana & "ÇØ"
		Case "ÉQ"
			StrConvHiragana = StrConvHiragana & "Ç∞"
		Case "ÉR"
			StrConvHiragana = StrConvHiragana & "Ç±"
		Case "ÉS"
			StrConvHiragana = StrConvHiragana & "Ç≤"
		Case "ÉT"
			StrConvHiragana = StrConvHiragana & "Ç≥"
		Case "ÉU"
			StrConvHiragana = StrConvHiragana & "Ç¥"
		Case "ÉV"
			StrConvHiragana = StrConvHiragana & "Çµ"
		Case "ÉW"
			StrConvHiragana = StrConvHiragana & "Ç∂"
		Case "ÉX"
			StrConvHiragana = StrConvHiragana & "Ç∑"
		Case "ÉY"
			StrConvHiragana = StrConvHiragana & "Ç∏"
		Case "ÉZ"
			StrConvHiragana = StrConvHiragana & "Çπ"
		Case "É["
			StrConvHiragana = StrConvHiragana & "Ç∫"
		Case "É\"
			StrConvHiragana = StrConvHiragana & "Çª"
		Case "É]"
			StrConvHiragana = StrConvHiragana & "Çº"
		Case "É^"
			StrConvHiragana = StrConvHiragana & "ÇΩ"
		Case "É_"
			StrConvHiragana = StrConvHiragana & "Çæ"
		Case "É`"
			StrConvHiragana = StrConvHiragana & "Çø"
		Case "Éa"
			StrConvHiragana = StrConvHiragana & "Ç¿"
		Case "Éb"
			StrConvHiragana = StrConvHiragana & "Ç¡"
		Case "Éc"
			StrConvHiragana = StrConvHiragana & "Ç¬"
		Case "Éd"
			StrConvHiragana = StrConvHiragana & "Ç√"
		Case "Ée"
			StrConvHiragana = StrConvHiragana & "Çƒ"
		Case "Éf"
			StrConvHiragana = StrConvHiragana & "Ç≈"
		Case "Ég"
			StrConvHiragana = StrConvHiragana & "Ç∆"
		Case "Éh"
			StrConvHiragana = StrConvHiragana & "Ç«"
		Case "Éi"
			StrConvHiragana = StrConvHiragana & "Ç»"
		Case "Éj"
			StrConvHiragana = StrConvHiragana & "Ç…"
		Case "Ék"
			StrConvHiragana = StrConvHiragana & "Ç "
		Case "Él"
			StrConvHiragana = StrConvHiragana & "ÇÀ"
		Case "Ém"
			StrConvHiragana = StrConvHiragana & "ÇÃ"
		Case "Én"
			StrConvHiragana = StrConvHiragana & "ÇÕ"
		Case "Éo"
			StrConvHiragana = StrConvHiragana & "ÇŒ"
		Case "Ép"
			StrConvHiragana = StrConvHiragana & "Çœ"
		Case "Éq"
			StrConvHiragana = StrConvHiragana & "Ç–"
		Case "Ér"
			StrConvHiragana = StrConvHiragana & "Ç—"
		Case "És"
			StrConvHiragana = StrConvHiragana & "Ç“"
		Case "Ét"
			StrConvHiragana = StrConvHiragana & "Ç”"
		Case "Éu"
			StrConvHiragana = StrConvHiragana & "Ç‘"
		Case "Év"
			StrConvHiragana = StrConvHiragana & "Ç’"
		Case "Éw"
			StrConvHiragana = StrConvHiragana & "Ç÷"
		Case "Éx"
			StrConvHiragana = StrConvHiragana & "Ç◊"
		Case "Éy"
			StrConvHiragana = StrConvHiragana & "Çÿ"
		Case "Éz"
			StrConvHiragana = StrConvHiragana & "ÇŸ"
		Case "É{"
			StrConvHiragana = StrConvHiragana & "Ç⁄"
		Case "É|"
			StrConvHiragana = StrConvHiragana & "Ç€"
		Case "É}"
			StrConvHiragana = StrConvHiragana & "Ç‹"
		Case "É~"
			StrConvHiragana = StrConvHiragana & "Ç›"
		Case "ÉÄ"
			StrConvHiragana = StrConvHiragana & "Çﬁ"
		Case "ÉÅ"
			StrConvHiragana = StrConvHiragana & "Çﬂ"
		Case "ÉÇ"
			StrConvHiragana = StrConvHiragana & "Ç‡"
		Case "ÉÉ"
			StrConvHiragana = StrConvHiragana & "Ç·"
		Case "ÉÑ"
			StrConvHiragana = StrConvHiragana & "Ç‚"
		Case "ÉÖ"
			StrConvHiragana = StrConvHiragana & "Ç„"
		Case "ÉÜ"
			StrConvHiragana = StrConvHiragana & "Ç‰"
		Case "Éá"
			StrConvHiragana = StrConvHiragana & "ÇÂ"
		Case "Éà"
			StrConvHiragana = StrConvHiragana & "ÇÊ"
		Case "Éâ"
			StrConvHiragana = StrConvHiragana & "ÇÁ"
		Case "Éä"
			StrConvHiragana = StrConvHiragana & "ÇË"
		Case "Éã"
			StrConvHiragana = StrConvHiragana & "ÇÈ"
		Case "Éå"
			StrConvHiragana = StrConvHiragana & "ÇÍ"
		Case "Éç"
			StrConvHiragana = StrConvHiragana & "ÇÎ"
		Case "Éé"
			StrConvHiragana = StrConvHiragana & "ÇÏ"
		Case "Éè"
			StrConvHiragana = StrConvHiragana & "ÇÌ"
		Case "Éê"
			StrConvHiragana = StrConvHiragana & "ÇÓ"
		Case "Éë"
			StrConvHiragana = StrConvHiragana & "ÇÔ"
		Case "Éí"
			StrConvHiragana = StrConvHiragana & "Ç"
		Case "Éì"
			StrConvHiragana = StrConvHiragana & "ÇÒ"
		Case Else
			StrConvHiragana = StrConvHiragana & sChr
		End Select
	Next
End Function

'***************************************************
' StrConvUnicode
'---------------------------------------------------
' ópìr : StrConv(s,vbUnicode) ÇÃÉNÉçÅ[Éì
' à¯êî : ïœä∑Ç∑ÇÈï∂éöóÒ
' ñﬂíl : ïœä∑Ç≥ÇÍÇΩï∂éöóÒ
'***************************************************
Function StrConvUnicode(sInp)
	Dim nCnt
	Dim nLen
	Dim nAsc
	Dim nChr
	nLen = LenB(sInp)
	For nCnt = 1 To nLen
		nAsc = AscB(MidB(sInp, nCnt, 1))
		If (&h81 <= nAsc And nAsc <= &h9F) Or (&hE0 <= nAsc And nAsc <= &hEF) Then
			nChr = nAsc * 256 + AscB(MidB(sInp, nCnt+1, 1))
			StrConvUnicode = StrConvUnicode & Chr(nChr)
			nCnt = nCnt + 1
		Else
			StrConvUnicode = StrConvUnicode & Chr(AscB(MidB(sInp, nCnt, 1)))
		End If
	Next
End Function

'***************************************************
' StrConvFromUnicode
'---------------------------------------------------
' ópìr : StrConv(s,vbFromUnicode) ÇÃÉNÉçÅ[Éì
' à¯êî : ïœä∑Ç∑ÇÈï∂éöóÒ
' ñﬂíl : ïœä∑Ç≥ÇÍÇΩï∂éöóÒ
'***************************************************
Function StrConvFromUnicode(sInp)
	Dim nCnt
	Dim nLen
	Dim nAsc
	nLen = Len(sInp)
	For nCnt = 1 to nLen
		nAsc = Asc(Mid(sInp, nCnt, 1))
		If nAsc And &hFF00 Then
			StrConvFromUnicode = StrConvFromUnicode & ChrB(Int(nAsc / 256) And &hFF)
			StrConvFromUnicode = StrConvFromUnicode & ChrB(nAsc And &hFF)
		Else
			StrConvFromUnicode = StrConvFromUnicode & ChrB(nAsc)
		End If
	Next
End Function

'***************************************************
' StrConv Ç™égópÇ∑ÇÈíËêîåS
'***************************************************
' Enum VbStrConv
Const vbUpperCase=1
Const vbLowerCase=2
Const vbProperCase=3
Const vbWide=4
Const vbNarrow=8
Const vbKatakana=16
Const vbHiragana=32
Const vbUnicode = 64
Const vbFromUnicode = 128

'***************************************************
' StrConv
'---------------------------------------------------
' à¯êî : ïœä∑Ç∑ÇÈï∂éöóÒ,ïœä∑èàóù
' ñﬂíl : ïœä∑Ç≥ÇÍÇΩï∂éöóÒ
'***************************************************
Function StrConv(sInp,eCnv)
	StrConv = sInp
	' Cnv Ç…ëŒÇµÇƒèàóùÇêUÇËï™ÇØ
	If eCnv And vbUpperCase Then
		StrConv = StrConvUpperCase(StrConv)
	End If
	If eCnv And vbLowerCase Then
		StrConv = StrConvLowerCase(StrConv)
	End If
	If eCnv = vbProperCase Then
		StrConv = StrConvProperCase(StrConv)
	End If
	If eCnv And vbWide Then
		StrConv = StrConvWide(StrConv)
	End If
	If eCnv And vbNarrow Then
		StrConv = StrConvNarrow(StrConv)
	End If
	If eCnv And vbKatakana Then
		StrConv = StrConvKatakana(StrConv)
	End If
	If eCnv And vbHiragana Then
		StrConv = StrConvHiragana(StrConv)
	End If
	If eCnv And vbUnicode Then
		StrConv = StrConvUnicode(StrConv)
	End If
	If eCnv And vbFromUnicode Then
		StrConv = StrConvFromUnicode(StrConv)
	End If
End Function


Function FileListing( objFolder )
	'WScript.Echo LenB( StrConvFromUnicode( objFolder.Path ) ) & " : " & objFolder.Path & "\"
	If LenB( StrConvFromUnicode( objFolder.Path ) ) > 240 Then
		WScript.Echo "240 OVER!! " & LenB( StrConvFromUnicode( objFolder.Path ) ) & " : " & objFolder.Path & "\"
		Exit Function
	End If

	For Each objSubFolder In objFolder.SubFolders
		FileListing( objSubFolder )
	Next

	For Each objFile In objFolder.Files
		'WScript.Echo LenB( StrConvFromUnicode( objFile.Path ) ) & " : " & objFile.Path
		If LenB( StrConvFromUnicode( objFile.Path ) ) > 240 Then
			WScript.Echo "240 OVER!! " & LenB( StrConvFromUnicode( objFile.Path ) ) & " : " & objFile.Path
			WScript.Echo "240 OVER!!"
			WScript.Quit
		End If
	Next
End Function


Set objFS = WScript.CreateObject( "Scripting.FileSystemObject" )

FileListing( objFS.GetFolder( WScript.Arguments.Item(0) ) )

