PROG	= clf
OBJS	= clf.o getopt.o getopt1.o

clean:
	rm *.o *~

$(PROG): $(OBJS)
	$(CC) -o $(PROG) $(OBJS)

# DO NOT DELETE

clf.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/features.h
clf.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
clf.o: /usr/include/_G_config.h /usr/include/gnu/types.h
clf.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
clf.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
clf.o: /usr/include/stdio_lim.h /usr/include/stdlib.h
clf.o: /usr/include/sys/types.h /usr/include/time.h /usr/include/endian.h
clf.o: /usr/include/bytesex.h /usr/include/sys/select.h
clf.o: /usr/include/selectbits.h /usr/include/alloca.h /usr/include/string.h
clf.o: /usr/include/fcntl.h /usr/include/fcntlbits.h getopt.h
getopt.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/features.h
getopt.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
getopt.o: /usr/include/_G_config.h /usr/include/gnu/types.h
getopt.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
getopt.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
getopt.o: /usr/include/stdio_lim.h
getopt1.o: getopt.h /usr/include/stdio.h /usr/include/libio.h
getopt1.o: /usr/include/features.h /usr/include/sys/cdefs.h
getopt1.o: /usr/include/gnu/stubs.h /usr/include/_G_config.h
getopt1.o: /usr/include/gnu/types.h
getopt1.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
getopt1.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
getopt1.o: /usr/include/stdio_lim.h
