Attribute VB_Name = "Module1"
Option Explicit

Public Declare Function GetTickCount Lib "kernel32" () As Long

Public g_strSQL As String

Sub InitSQL()

    g_strSQL = ""
    
g_strSQL = g_strSQL & "    SELECT"
g_strSQL = g_strSQL & "        A.*,"
g_strSQL = g_strSQL & "        B.MODE_BANGO,"
g_strSQL = g_strSQL & "        B.RANK_MEI_1,"
g_strSQL = g_strSQL & "        B.RANK_DATE_1,"
g_strSQL = g_strSQL & "        B.RANK_MEI_2,"
g_strSQL = g_strSQL & "        B.RANK_DATE_2,"
g_strSQL = g_strSQL & "        B.RANK_MEI_3,"
g_strSQL = g_strSQL & "        B.RANK_DATE_3,"
g_strSQL = g_strSQL & "        B.KUGI_SIJI,"
g_strSQL = g_strSQL & "        B.MODE_SIJI"
g_strSQL = g_strSQL & "    From"
g_strSQL = g_strSQL & "        VW_USE_DV_DATA_FILE A,"
g_strSQL = g_strSQL & "        KUGI_RANK_INPUT B"
g_strSQL = g_strSQL & "    Where"
g_strSQL = g_strSQL & "        A.TENPO_BANGO = B.TENPO_BANGO"
g_strSQL = g_strSQL & "        AND"
g_strSQL = g_strSQL & "        A.DV_DATE = B.KEY_DATE"
g_strSQL = g_strSQL & "        AND"
g_strSQL = g_strSQL & "        A.DAI_BANGO = B.DAI_BANGO"

End Sub

Sub InitSQL2()

g_strSQL = ""
g_strSQL = g_strSQL & "SELECT "
g_strSQL = g_strSQL & " DV_DATE,"
g_strSQL = g_strSQL & " DAI_BANGO,"
g_strSQL = g_strSQL & " SHIMA_BANGO,"
g_strSQL = g_strSQL & " KISHU_ID,"
g_strSQL = g_strSQL & " KISHU_NO,"
g_strSQL = g_strSQL & " RANK_DATE_1,"
g_strSQL = g_strSQL & " KUGI_SIJI,"
g_strSQL = g_strSQL & " SUM(DV_SUM010) AS SUM_DV_SUM010,"
g_strSQL = g_strSQL & " SUM(DV_SUM010) AS DV_SUM010,"
g_strSQL = g_strSQL & " SUM(DV_SUM030) AS SUM_DV_SUM030,"
g_strSQL = g_strSQL & " SUM(DV_SUM030) AS DV_SUM030,"
g_strSQL = g_strSQL & " SUM(DV_SUM020) AS SUM_DV_SUM020,"
g_strSQL = g_strSQL & " SUM(DV_SUM020) AS DV_SUM020,"
g_strSQL = g_strSQL & " SUM(DV_SUM720) AS SUM_DV_SUM720,"
g_strSQL = g_strSQL & " SUM(DV_SUM720) AS DV_SUM720,"
g_strSQL = g_strSQL & " SUM(DV_SUM090) AS SUM_DV_SUM090,"
g_strSQL = g_strSQL & " SUM(DV_SUM090) AS DV_SUM090,"
g_strSQL = g_strSQL & " SUM(DV_SUM100) AS SUM_DV_SUM100,"
g_strSQL = g_strSQL & " SUM(DV_SUM100) AS DV_SUM100,"
g_strSQL = g_strSQL & " SUM(DV_SUM110) AS SUM_DV_SUM110,"
g_strSQL = g_strSQL & " SUM(DV_SUM110) AS DV_SUM110,"
g_strSQL = g_strSQL & " SUM(DV_SUM120) AS SUM_DV_SUM120,"
g_strSQL = g_strSQL & " SUM(DV_SUM120) AS DV_SUM120,"
g_strSQL = g_strSQL & " SUM(DV_SUM130) AS SUM_DV_SUM130,"
g_strSQL = g_strSQL & " SUM(DV_SUM130) AS DV_SUM130,"
g_strSQL = g_strSQL & " SUM(DV_SUM140) AS SUM_DV_SUM140,"
g_strSQL = g_strSQL & " SUM(DV_SUM140) AS DV_SUM140,"
g_strSQL = g_strSQL & " SUM(DV_SUM150) AS SUM_DV_SUM150,"
g_strSQL = g_strSQL & " SUM(DV_SUM150) AS DV_SUM150,"
g_strSQL = g_strSQL & " SUM(DV_SUM210) AS SUM_DV_SUM210,"
g_strSQL = g_strSQL & " SUM(DV_SUM210) AS DV_SUM210,"
g_strSQL = g_strSQL & " SUM(DV_SUM040) AS SUM_DV_SUM040,"
g_strSQL = g_strSQL & " SUM(DV_SUM040) AS DV_SUM040,"
g_strSQL = g_strSQL & " SUM(DV_SUM240) AS SUM_DV_SUM240,"
g_strSQL = g_strSQL & " SUM(DV_SUM240) AS DV_SUM240,"
g_strSQL = g_strSQL & " SUM(DV_SUM300) AS SUM_DV_SUM300,"
g_strSQL = g_strSQL & " SUM(DV_SUM300) AS DV_SUM300,"
g_strSQL = g_strSQL & " SUM(DV_SUM320) AS SUM_DV_SUM320,"
g_strSQL = g_strSQL & " SUM(DV_SUM320) AS DV_SUM320,"
g_strSQL = g_strSQL & " SUM(DV_SUM607) AS SUM_DV_SUM607,"
g_strSQL = g_strSQL & " SUM(DV_SUM607) AS DV_SUM607,"
g_strSQL = g_strSQL & " SUM(DV_SUM330) AS SUM_DV_SUM330,"
g_strSQL = g_strSQL & " SUM(DV_SUM330) AS DV_SUM330,"
g_strSQL = g_strSQL & " SUM(DV_SUM350) AS SUM_DV_SUM350,"
g_strSQL = g_strSQL & " SUM(DV_SUM350) AS DV_SUM350,"
g_strSQL = g_strSQL & " SUM(DV_SUM360) AS SUM_DV_SUM360,"
g_strSQL = g_strSQL & " SUM(DV_SUM360) AS DV_SUM360,"
g_strSQL = g_strSQL & " SUM(DV_SUM420) AS SUM_DV_SUM420,"
g_strSQL = g_strSQL & " SUM(DV_SUM420) AS DV_SUM420,"
g_strSQL = g_strSQL & " SUM(DV_SUM510) AS SUM_DV_SUM510,"
g_strSQL = g_strSQL & " SUM(DV_SUM510) AS DV_SUM510,"
g_strSQL = g_strSQL & " SUM(DV_SUM712) AS SUM_DV_SUM712,"
g_strSQL = g_strSQL & " SUM(DV_SUM712) AS DV_SUM712,"
g_strSQL = g_strSQL & " SUM(DV_SUM702) AS SUM_DV_SUM702,"
g_strSQL = g_strSQL & " SUM(DV_SUM702) AS DV_SUM702,"
g_strSQL = g_strSQL & " SUM(DV_SUM750) AS SUM_DV_SUM750,"
g_strSQL = g_strSQL & " SUM(DV_SUM750) AS DV_SUM750,"
g_strSQL = g_strSQL & " SUM(DV_SUM760) AS SUM_DV_SUM760,"
g_strSQL = g_strSQL & " SUM(DV_SUM760) AS DV_SUM760,"
g_strSQL = g_strSQL & " SUM(DV_DAI_COUNT) DV_DAI_COUNT "
g_strSQL = g_strSQL & "FROM  "
g_strSQL = g_strSQL & " ("
g_strSQL = g_strSQL & " SELECT "
g_strSQL = g_strSQL & "     A.*,"
g_strSQL = g_strSQL & "     B.MODE_BANGO,"
g_strSQL = g_strSQL & "     B.RANK_MEI_1,"
g_strSQL = g_strSQL & "     B.RANK_DATE_1,"
g_strSQL = g_strSQL & "     B.RANK_MEI_2,"
g_strSQL = g_strSQL & "     B.RANK_DATE_2,"
g_strSQL = g_strSQL & "     B.RANK_MEI_3,"
g_strSQL = g_strSQL & "     B.RANK_DATE_3,"
g_strSQL = g_strSQL & "     B.KUGI_SIJI,"
g_strSQL = g_strSQL & "     B.MODE_SIJI "
g_strSQL = g_strSQL & " FROM "
g_strSQL = g_strSQL & "     VW_USE_DV_DATA_FILE A,"
g_strSQL = g_strSQL & "     KUGI_RANK_INPUT B "
g_strSQL = g_strSQL & " WHERE "
g_strSQL = g_strSQL & "     A.TENPO_BANGO = B.TENPO_BANGO "
g_strSQL = g_strSQL & "     AND "
g_strSQL = g_strSQL & "     A.DV_DATE = B.KEY_DATE "
g_strSQL = g_strSQL & "     AND "
g_strSQL = g_strSQL & "     A.DAI_BANGO = B.DAI_BANGO"
g_strSQL = g_strSQL & " )  "
g_strSQL = g_strSQL & "WHERE "
g_strSQL = g_strSQL & " TENPO_BANGO=1 "
g_strSQL = g_strSQL & " AND "
g_strSQL = g_strSQL & " DV_DATE>= TO_DATE('20061111','YYYYMMDD')  "
g_strSQL = g_strSQL & " AND "
g_strSQL = g_strSQL & " DV_DATE<= TO_DATE('20061124','YYYYMMDD')  "
g_strSQL = g_strSQL & " AND "
g_strSQL = g_strSQL & " CALEN_JYOTAI=1 "
g_strSQL = g_strSQL & "GROUP BY "
g_strSQL = g_strSQL & " DV_DATE,"
g_strSQL = g_strSQL & " DAI_BANGO,"
g_strSQL = g_strSQL & " SHIMA_BANGO,"
g_strSQL = g_strSQL & " KISHU_ID,"
g_strSQL = g_strSQL & " KISHU_NO,"
g_strSQL = g_strSQL & " RANK_DATE_1,"
g_strSQL = g_strSQL & " KUGI_SIJI "
g_strSQL = g_strSQL & "ORDER BY "
g_strSQL = g_strSQL & " KISHU_NO, "
g_strSQL = g_strSQL & " DAI_BANGO,"
g_strSQL = g_strSQL & " DV_DATE DESC"

End Sub

Sub InitSQL3()
    Dim fno As Integer
    
    fno = FreeFile
    Open "d:\work\sql.txt" For Input As fno
    Line Input #fno, g_strSQL
    Close fno
    
End Sub
