# THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
# ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
# PARTICULAR PURPOSE.
#
# Copyright (C) 1993 - 1995  Microsoft Corporation.  All Rights Reserved.
#
#
# Processor independent makefile

# Nmake macros for building Windows 32-Bit apps
!include <ntwin32.mak>

PROJ = appbar

all: $(PROJ).exe

# Define project specific macros
PROJ_OBJS  = main.obj wndproc.obj appbar.obj propsheet.obj util.obj
EXTRA_LIBS = version.lib comctl32.lib shell32.lib
GLOBAL_DEP = globals.h resource.h appbar.h
RC_DEP     = resource.h res/appbar.ico res/appbar.bmp res/base.bmp res/window.bmp

# Dependencies
main.obj:      main.c      $(GLOBAL_DEP)
wndproc.obj:   wndproc.c   $(GLOBAL_DEP)
appbar.obj:    appbar.c	   $(GLOBAL_DEP)
propsheet.obj: propsheet.c $(GLOBAL_DEP)
util.obj:      util.c      $(GLOBAL_DEP)

# Inference rule for updating the object files
.c.obj:
  $(cc) $(cdebug) $(cflags) $(cvars) $*.c

# Build rule for resource file
$(PROJ).res: $(PROJ).rc $(RC_DEP)
    $(rc) $(rcflags) $(rcvars) /fo $(PROJ).res $(PROJ).rc

# Build rule for EXE
$(PROJ).EXE: $(PROJ_OBJS) $(PROJ).res
    $(link) $(linkdebug) $(guilflags) \
    $(BASE_OBJS) $(PROJ_OBJS) $(PROJ).res $(guilibs) $(EXTRA_LIBS) \
    -out:$(PROJ).exe $(MAPFILE)



# Rules for cleaning out those old files
clean:
    del *.bak 
    del *.pdb 
    del *.obj 
    del *.res 
    del *.exp 
    del *.map 
    del *.sbr 
    del *.bsc

