//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PipeSample.rc
//
#define IDD_MAIN                        101
#define IDI_APPL                        102
#define IDC_RUN_EXE                     1000
#define IDC_RUN_COM                     1001
#define IDC_RUN_COM_ON_BASH             1002
#define IDC_FORMAT                      1003
#define IDC_FORMAT_ON_BASH              1004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
